// Les 48 qualifiés — noms exacts du feed fixturedownload → drapeau (flagcdn), noms FR/EN, trigramme FIFA
const TEAMS = {
  'Algeria':                { code: 'dz',     fr: 'Algérie',            en: 'Algeria',             tri: 'ALG' },
  'Argentina':              { code: 'ar',     fr: 'Argentine',          en: 'Argentina',           tri: 'ARG' },
  'Australia':              { code: 'au',     fr: 'Australie',          en: 'Australia',           tri: 'AUS' },
  'Austria':                { code: 'at',     fr: 'Autriche',           en: 'Austria',             tri: 'AUT' },
  'Belgium':                { code: 'be',     fr: 'Belgique',           en: 'Belgium',             tri: 'BEL' },
  'Bosnia and Herzegovina': { code: 'ba',     fr: 'Bosnie-Herzégovine', en: 'Bosnia & Herzegovina', tri: 'BIH' },
  'Brazil':                 { code: 'br',     fr: 'Brésil',             en: 'Brazil',              tri: 'BRA' },
  'Cabo Verde':             { code: 'cv',     fr: 'Cap-Vert',           en: 'Cape Verde',          tri: 'CPV' },
  'Canada':                 { code: 'ca',     fr: 'Canada',             en: 'Canada',              tri: 'CAN' },
  'Colombia':               { code: 'co',     fr: 'Colombie',           en: 'Colombia',            tri: 'COL' },
  'Congo DR':               { code: 'cd',     fr: 'RD Congo',           en: 'DR Congo',            tri: 'COD' },
  'Croatia':                { code: 'hr',     fr: 'Croatie',            en: 'Croatia',             tri: 'CRO' },
  'Curaçao':                { code: 'cw',     fr: 'Curaçao',            en: 'Curaçao',             tri: 'CUW' },
  'Czechia':                { code: 'cz',     fr: 'Tchéquie',           en: 'Czechia',             tri: 'CZE' },
  "Côte d'Ivoire":          { code: 'ci',     fr: "Côte d'Ivoire",      en: 'Ivory Coast',         tri: 'CIV' },
  'Ecuador':                { code: 'ec',     fr: 'Équateur',           en: 'Ecuador',             tri: 'ECU' },
  'Egypt':                  { code: 'eg',     fr: 'Égypte',             en: 'Egypt',               tri: 'EGY' },
  'England':                { code: 'gb-eng', fr: 'Angleterre',         en: 'England',             tri: 'ENG' },
  'France':                 { code: 'fr',     fr: 'France',             en: 'France',              tri: 'FRA' },
  'Germany':                { code: 'de',     fr: 'Allemagne',          en: 'Germany',             tri: 'GER' },
  'Ghana':                  { code: 'gh',     fr: 'Ghana',              en: 'Ghana',               tri: 'GHA' },
  'Haiti':                  { code: 'ht',     fr: 'Haïti',              en: 'Haiti',               tri: 'HAI' },
  'IR Iran':                { code: 'ir',     fr: 'Iran',               en: 'Iran',                tri: 'IRN' },
  'Iraq':                   { code: 'iq',     fr: 'Irak',               en: 'Iraq',                tri: 'IRQ' },
  'Japan':                  { code: 'jp',     fr: 'Japon',              en: 'Japan',               tri: 'JPN' },
  'Jordan':                 { code: 'jo',     fr: 'Jordanie',           en: 'Jordan',              tri: 'JOR' },
  'Korea Republic':         { code: 'kr',     fr: 'Corée du Sud',       en: 'South Korea',         tri: 'KOR' },
  'Mexico':                 { code: 'mx',     fr: 'Mexique',            en: 'Mexico',              tri: 'MEX' },
  'Morocco':                { code: 'ma',     fr: 'Maroc',              en: 'Morocco',             tri: 'MAR' },
  'Netherlands':            { code: 'nl',     fr: 'Pays-Bas',           en: 'Netherlands',         tri: 'NED' },
  'New Zealand':            { code: 'nz',     fr: 'Nlle-Zélande',       en: 'New Zealand',         tri: 'NZL' },
  'Norway':                 { code: 'no',     fr: 'Norvège',            en: 'Norway',              tri: 'NOR' },
  'Panama':                 { code: 'pa',     fr: 'Panama',             en: 'Panama',              tri: 'PAN' },
  'Paraguay':               { code: 'py',     fr: 'Paraguay',           en: 'Paraguay',            tri: 'PAR' },
  'Portugal':               { code: 'pt',     fr: 'Portugal',           en: 'Portugal',            tri: 'POR' },
  'Qatar':                  { code: 'qa',     fr: 'Qatar',              en: 'Qatar',               tri: 'QAT' },
  'Saudi Arabia':           { code: 'sa',     fr: 'Arabie saoudite',    en: 'Saudi Arabia',        tri: 'KSA' },
  'Scotland':               { code: 'gb-sct', fr: 'Écosse',             en: 'Scotland',            tri: 'SCO' },
  'Senegal':                { code: 'sn',     fr: 'Sénégal',            en: 'Senegal',             tri: 'SEN' },
  'South Africa':           { code: 'za',     fr: 'Afrique du Sud',     en: 'South Africa',        tri: 'RSA' },
  'Spain':                  { code: 'es',     fr: 'Espagne',            en: 'Spain',               tri: 'ESP' },
  'Sweden':                 { code: 'se',     fr: 'Suède',              en: 'Sweden',              tri: 'SWE' },
  'Switzerland':            { code: 'ch',     fr: 'Suisse',             en: 'Switzerland',         tri: 'SUI' },
  'Tunisia':                { code: 'tn',     fr: 'Tunisie',            en: 'Tunisia',             tri: 'TUN' },
  'Türkiye':                { code: 'tr',     fr: 'Turquie',            en: 'Türkiye',             tri: 'TUR' },
  'USA':                    { code: 'us',     fr: 'États-Unis',         en: 'USA',                 tri: 'USA' },
  'Uruguay':                { code: 'uy',     fr: 'Uruguay',            en: 'Uruguay',             tri: 'URU' },
  'Uzbekistan':             { code: 'uz',     fr: 'Ouzbékistan',        en: 'Uzbekistan',          tri: 'UZB' },
};

module.exports = { TEAMS };
